Sequel.migration do
  up do
    areas = DB[:areas]
    areas.insert(name: 'email',  size: 'large')
    areas.insert(name: 'campaigns_acc', size: 'large')
    areas.insert(name: 'account', size: 'large')
    areas.insert(name: 'landing_page',  size: 'large')
    areas.insert(name: 'contact', size: 'large')
    areas.insert(name: 'campaign2', size: 'large')
    areas.insert(name: 'dynamic_content', size: 'large')
    areas.insert(name: 'field_merge', size: 'large')
    areas.insert(name: 'email_header_footer', size: 'large')
    areas.insert(name: 'file_storage',  size: 'large')
    areas.insert(name: 'hyperlink', size: 'large')
    areas.insert(name: 'image_upload',  size: 'large')
    areas.insert(name: 'form',  size: 'large')
    areas.insert(name: 'mailer',  size: 'large')
    areas.insert(name: 'shared_library',  size: 'large')
    areas.insert(name: 'shared_content',  size: 'large')
    areas.insert(name: 'account', size: 'medium')
    areas.insert(name: 'contact', size: 'medium')
    areas.insert(name: 'data_import_export',  size: 'medium')
    areas.insert(name: 'segment', size: 'large')
    areas.insert(name: 'dynamic_content', size: 'medium')
    areas.insert(name: 'email_footer',  size: 'medium')
    areas.insert(name: 'email_header',  size: 'medium')
    areas.insert(name: 'field_merge', size: 'medium')
    areas.insert(name: 'email', size: 'medium')
    areas.insert(name: 'file_storage',  size: 'medium')
    areas.insert(name: 'hyperlink', size: 'medium')
    areas.insert(name: 'image', size: 'medium')
    areas.insert(name: 'form',  size: 'medium')
    areas.insert(name: 'simple_campaign', size: 'large')
    areas.insert(name: 'mailer',  size: 'medium')
    areas.insert(name: 'launchpad', size: 'medium')
    areas.insert(name: 'shared_content',  size: 'medium')
    areas.insert(name: 'shared_filter', size: 'medium')
    areas.insert(name: 'landing_page',  size: 'medium')
    areas.insert(name: 'segment', size: 'medium')
    areas.insert(name: 'shared_update_rule',  size: 'medium')
    areas.insert(name: 'account', size: 'small')
    areas.insert(name: 'shared_list', size: 'medium')
    areas.insert(name: 'contact', size: 'small')
    areas.insert(name: 'campaign',  size: 'small')
    areas.insert(name: 'contacts_upload_add_contacts_to_database',  size: 'small')
    areas.insert(name: 'contacts_upload_mark_as_bounceback',  size: 'small')
    areas.insert(name: 'contacts_upload_unsubscribe', size: 'small')
    areas.insert(name: 'dashboard', size: 'small')
    areas.insert(name: 'content_loss',  size: 'small')
    areas.insert(name: 'email_upload',  size: 'small')
    areas.insert(name: 'email', size: 'small')
    areas.insert(name: 'campaign_hotfixes', size: 'small')
    areas.insert(name: 'form',  size: 'small')
    areas.insert(name: 'form_integration',  size: 'small')
    areas.insert(name: 'global_search_help',  size: 'small')
    areas.insert(name: 'form_hotfixes', size: 'small')
    areas.insert(name: 'landing_page_upload', size: 'small')
    areas.insert(name: 'landing_page',  size: 'small')
    areas.insert(name: 'launchpad', size: 'small')
    areas.insert(name: 'lead_scoring',  size: 'small')
    areas.insert(name: 'mailer',  size: 'small')
    areas.insert(name: 'settings_assets_email_defaults',  size: 'small')
    areas.insert(name: 'reporting', size: 'small')
    areas.insert(name: 'segment', size: 'small')

    areas.update(display_name: :name) # set the initial values for display_name
  end

  down do
    DB[:areas].delete
  end
end